
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

/* Files required for transport initialization. */
#include <coresrv/nk/transport-kos.h>
#include <coresrv/sl/sl_api.h>

/* EDL description of the server entity. */
#include <echo/IPing.idl.h>
#include <echo/CPing.cdl.h>
#include <echo/Server.edl.h>

#include <assert.h>

/* FPing method implementation, name matches IPing.idl. */
static nk_err_t FPing_impl(struct echo_IPing *self,  
                          const echo_IPing_FPing_req *req, // argument types are also autogenerated
                          const struct nk_arena* req_arena,
                          echo_IPing_FPing_res* res,
                          struct nk_arena* res_arena)
{
    /* Function implementation.
     * req+req_arena are arguments, and res+res_arena
     * sent to the client in the server response. */ 
    res->result = req->value + 3; // Increment is set as constant for simplification
    fprintf(stderr, "[Server] request %d, result %d\n", (int) req->value, (int) res->result);       
    return NK_EOK;
}

/* IPing interface object constructor. Should include
 * references for all interface functions implementations. */
static struct echo_IPing *CreateIPingImpl(void)
{
    /* Table of implementations of IPing interface methods. */
    static const struct echo_IPing_ops ops = {
        .FPing = FPing_impl  // left part must match function name from IDL
    };

    /* Interface itself equals to pointer to the table of pointers. */
    static echo_IPing obj = {
        .ops = &ops
    };

    return &obj;
}

/* Server entry point. */
int main(void)
{
    NkKosTransport transport;
    ServiceId iid;

    /* Get server IPC handle of "server_connection". */
    Handle handle = ServiceLocatorRegister("server_connection", NULL, 0, &iid);
    assert(handle != INVALID_HANDLE);

    /* Initialize transport to client. */
    NkKosTransport_Init(&transport, handle, NK_NULL, 0);

    /* Prepare the structures of the request to the server entity: constant
     * part and arena. Because none of the methods of the server entity has
     * sequence type arguments, only constant parts of the
     * request and response are used. Arenas are effectively unused. However,
     * valid arenas of the request and response must be passed to
     * server transport methods (nk_transport_recv, nk_transport_reply) and
     * to the server_entity_dispatch method. */
    echo_Server_entity_req req;
    char req_buffer[echo_Server_entity_req_arena_size];
    struct nk_arena req_arena = NK_ARENA_INITIALIZER(req_buffer, req_buffer + sizeof(req_buffer));

    /* Prepare response structures: constant part and arena. */
    echo_Server_entity_res res;
    char res_buffer[echo_Server_entity_res_arena_size];
    struct nk_arena res_arena = NK_ARENA_INITIALIZER(res_buffer, res_buffer + sizeof(res_buffer));

    /* Initialize ping component dispatcher. 3 is the value of the step,
     * which is the number by which the input value is increased. */
    echo_CPing_component component;
    echo_CPing_component_init(&component, CreateIPingImpl());

    /* Initialize server entity dispatcher. */
    echo_Server_entity entity;
    echo_Server_entity_init(&entity, &component);

    fprintf(stderr, "Hello I'm server\n");

    /* Dispatch loop implementation. */
    do
    {
        /* Flush request/response buffers.
         * No need to reset res part, it will be rewritten automatically. */
        nk_req_reset(&req);
        nk_arena_reset(&req_arena);
        nk_arena_reset(&res_arena);

        /* Wait for request to server entity. */
        if (nk_transport_recv(&transport.base, &req.base_, &req_arena) != NK_EOK) {
            fprintf(stderr, "nk_transport_recv error\n");
        } else {
            /* Handle received request by calling implementation FPing_impl
             * of the requested Ping interface method. */
            echo_Server_entity_dispatch(&entity, &req.base_, &req_arena, &res.base_, &res_arena);
        }

        /* Send response. */
        if (nk_transport_reply(&transport.base, &res.base_, &res_arena) != NK_EOK) {
            fprintf(stderr, "nk_transport_reply error\n");
        }
    }
    while (true);

    return EXIT_SUCCESS;
}
